CREATE TABLE PRODUCTS (
  PRODUCTID INT PRIMARY KEY IDENTITY(1,1),
  PRODUCTNAME NVARCHAR(100) NOT NULL,
  PRICE DECIMAL(10, 2) NOT NULL,
  STOCK INT NOT NULL
);

-- Sample data
INSERT INTO PRODUCTS (PRODUCTNAME, PRICE, STOCK)
VALUES 
('Apple', 1.99, 100),
('Banana', 0.99, 50),
('Orange', 2.49, 75);
